//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface SBWiFiManager : NSObject
{
    NSRecursiveLock *_lock;
    struct __WiFiManagerClient *_manager;
    struct __WiFiDeviceClient *_device;
    NSString *_deviceInterfaceName;
    BOOL _devicePresent;
    struct __WiFiNetwork *_currentNetwork;
    struct __WiFiNetwork *_previousNetwork;
    BOOL _currentNetworkHasBeenSet;
    BOOL _currentNetworkIsIOSHotspot;
    BOOL _currentNetworkIsIOSHotspotHasBeenSet;
    BOOL _powered;
    BOOL _poweredHasBeenSet;
    int _rssiThreshold;
    int _signalStrengthBars;
    int _signalStrengthRSSI;
    BOOL _signalStrengthHasBeenSet;
    struct __SCDynamicStore *_SCDynamicStoreNetworkState;
    NSObject *_SCUpdateTimeoutSource;
    struct __WiFiNetwork *_primaryInterface;
    BOOL _primaryInterfaceHasBeenSet;
    BOOL _isPrimaryInterface;
    BOOL _isPrimaryInterfaceChanging;
    int linkToken;
    int powerToken;
}

+ (id)sharedInstance;
- (void)_primaryInterfaceChanged:(BOOL)arg1;
- (void)_setPrimaryInterfaceHasBeenSet;
- (id)_wifiInterface;
- (BOOL)isPrimaryInterface;
- (void)resetSettings;
- (id)knownNetworks;
- (void)updateSignalStrength;
- (void)updateSignalStrengthFromRawRSSI:(int)arg1 andScaledRSSI:(CGFloat)arg2;
- (int)signalStrengthRSSI;
- (int)signalStrengthBars;
- (void)setWiFiEnabled:(BOOL)arg1;
- (BOOL)wiFiEnabled;
- (void)setPowered:(BOOL)arg1;
- (BOOL)isPowered;
- (id)currentNetworkName;
- (BOOL)_cachedIsAssociated;
- (BOOL)isAssociatedToIOSHotspot;
- (BOOL)isAssociated;
- (void)_updateCurrentNetwork;
- (void)_updateWiFiDevice:(id)arg1;
- (void)_linkDidChange;
- (void)_powerStateDidChange;
- (void)_updateWiFiState;
- (struct __WiFiManagerClient *)_manager;
- (void)_setWiFiDevice:(struct __WiFiDeviceClient *)arg1;
- (void)updateDevicePresence;
- (BOOL)devicePresent;
- (BOOL)wifiSupported;
- (id)init;

@end

